# Generated by Django 3.2.5 on 2021-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryevent',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
