# Generated by Django 3.2.5 on 2021-07-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210707_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('expiry_date', models.DateField()),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.RenameField(
            model_name='itemstatus',
            old_name='status_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='status_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
