# Generated by Django 3.2.5 on 2021-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='hover_image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image_url',
            field=models.URLField(max_length=500),
        ),
    ]
