# Generated by Django 3.2.5 on 2021-07-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_max_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
    ]
